version: '2'
services:
  mongo-database:
    image: mongo:latest
    container_name: calendly_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db


  mongo-express:
    image: mongo-express
    container_name: calendly_mongo_express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: calendly_database
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    depends_on:
      - mongo-database


 
  frontend_server:
    image: nginx
    container_name: calendly_nginx
    volumes:
#      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./ssl:/etc/nginx/ssl
    ports:
      - 80:80
#      - 443:443
  
  angular_server:
    image: node:16
    container_name: calendly_angular
    volumes:
      - ./client:/home/app
    working_dir: /home/app
    command: "sh run-dev.sh"



  backend_server:
    image: node:16
    container_name: calendly_backend
    volumes:
      - ./server:/home/app
      - ./logs:/root/.npm/_logs
    working_dir: /home/app
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://root:rootpassword@calendly_database/project_db?authSource=admin"

    command: "sh run-dev.sh"
    #command: "sleep infinity"

volumes:
  mongodb_data_container:
